// This file should ideally be generated by `npx supabase gen types typescript ...`
// For now, this is a manual representation based on your schema.
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export interface Database {
  public: {
    Tables: {
      companies: {
        Row: {
          address: string | null
          created_at: string | null
          id: string
          name: string
          registration_number: string | null
        }
        Insert: {
          address?: string | null
          created_at?: string | null
          id?: string
          name: string
          registration_number?: string | null
        }
        Update: {
          address?: string | null
          created_at?: string | null
          id?: string
          name?: string
          registration_number?: string | null
        }
        Relationships: []
      }
      contracts: {
        Row: {
          created_at: string | null
          form_values: Json | null
          generated_at: string | null
          generated_file_bucket: string
          generated_file_name: string
          generated_file_path: string
          id: string
          template_id: string
          user_id: string
        }
        Insert: {
          created_at?: string | null
          form_values?: Json | null
          generated_at?: string | null
          generated_file_bucket?: string
          generated_file_name: string
          generated_file_path: string
          id?: string
          template_id: string
          user_id: string
        }
        Update: {
          created_at?: string | null
          form_values?: Json | null
          generated_at?: string | null
          generated_file_bucket?: string
          generated_file_name?: string
          generated_file_path?: string
          id?: string
          template_id?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "contracts_template_id_fkey"
            columns: ["template_id"]
            referencedRelation: "templates"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "contracts_user_id_fkey"
            columns: ["user_id"]
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          avatar_url: string | null
          full_name: string | null
          id: string
          updated_at: string | null
        }
        Insert: {
          avatar_url?: string | null
          full_name?: string | null
          id: string
          updated_at?: string | null
        }
        Update: {
          avatar_url?: string | null
          full_name?: string | null
          id?: string
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "profiles_id_fkey"
            columns: ["id"]
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      promoters: {
        Row: {
          contact_email: string | null
          created_at: string | null
          id: string
          name: string
        }
        Insert: {
          contact_email?: string | null
          created_at?: string | null
          id?: string
          name: string
        }
        Update: {
          contact_email?: string | null
          created_at?: string | null
          id?: string
          name?: string
        }
        Relationships: []
      }
      templates: {
        Row: {
          created_at: string | null
          description: string | null
          docx_file_bucket: string
          docx_file_path: string
          id: string
          name: string
          placeholders_config: Json | null
          updated_at: string | null
        }
        Insert: {
          created_at?: string | null
          description?: string | null
          docx_file_bucket?: string
          docx_file_path: string
          id?: string
          name: string
          placeholders_config?: Json | null
          updated_at?: string | null
        }
        Update: {
          created_at?: string | null
          description?: string | null
          docx_file_bucket?: string
          docx_file_path?: string
          id?: string
          name?: string
          placeholders_config?: Json | null
          updated_at?: string | null
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      handle_new_user: {
        Args: Record<PropertyKey, never>
        Returns: Record<PropertyKey, never>
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}
